swagger: "2.0"
info: 
  version: "0.0.1"
  title: "subscriber api"
  description: "simple api for subscribers"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Cloudmesh community"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /Sub:
    post:
      description: 'creates or updates subscriber with name sub_name'
      
      produces:
        - 'application/json'
      responses:
        200:
            description: 'created or modified subscriber'
definitions:
  Sub:
    type: "object"
    required: 
      - "name"
      - "email"
    properties: 
      name:
        type: 'string'
      email:
        type: 'string'